# Stage 1:
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG REACT_APP_WS_URL
ARG REACT_APP_CLIENT_ID_GOOGLE
ARG REACT_APP_ENVIRONMENT
ARG REACT_APP_URL_PRO
ARG REACT_APP_ACCESS_KEY
ARG REACT_APP_URL_DEV
ARG REACT_APP_MAPBOX_CLIENTID

ENV REACT_APP_WS_URL=$REACT_APP_WS_URL
ENV REACT_APP_CLIENT_ID_GOOGLE=$REACT_APP_CLIENT_ID_GOOGLE
ENV REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
ENV REACT_APP_URL_PRO=$REACT_APP_URL_PRO
ENV REACT_APP_ACCESS_KEY=$REACT_APP_ACCESS_KEY
ENV REACT_APP_URL_DEV=$REACT_APP_URL_DEV
ENV REACT_APP_MAPBOX_CLIENTID=$REACT_APP_MAPBOX_CLIENTID
ENV NODE_OPTIONS=--max-old-space-size=4096
RUN npm run build

# Stage 2:
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
